# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-27 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daftar', '0002_auto_20190515_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daftarmodel',
            name='jenis_kelamin',
            field=models.CharField(choices=[('pria', 'Pria'), ('wanita', 'Wanita')], max_length=10),
        ),
        migrations.AlterField(
            model_name='daftarmodel',
            name='pendidikan_ortu',
            field=models.CharField(choices=[('sd', 'SD'), ('smp', 'SMP'), ('sma', 'SMA'), ('s1', 'S1'), ('s2', 'S2'), ('s3', 'S3')], max_length=15),
        ),
    ]
