# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-27 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daftar', '0003_auto_20190527_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daftarmodel',
            name='jenis_kelamin',
            field=models.CharField(choices=[('pria', 'Pria'), ('wanita', 'Wanita')], default='pria', max_length=10),
        ),
    ]
