# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-11 04:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nis', models.CharField(max_length=8)),
                ('nama', models.TextField(max_length=50)),
                ('tempat_lahir', models.TextField(max_length=20)),
            ],
        ),
    ]
