# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-11 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0002_siswa_waktuedit'),
    ]

    operations = [
        migrations.AddField(
            model_name='siswa',
            name='kelas',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='nama',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='tempat_lahir',
            field=models.CharField(max_length=15),
        ),
    ]
