# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-11 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0003_auto_20190511_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guru',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nik', models.CharField(max_length=10)),
                ('nama', models.CharField(max_length=50)),
                ('tempat_lahir', models.CharField(max_length=15)),
                ('alamat', models.CharField(max_length=50)),
            ],
        ),
    ]
