# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-12 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0004_guru'),
    ]

    operations = [
        migrations.AddField(
            model_name='siswa',
            name='slug',
            field=models.SlugField(blank=True, editable=False),
        ),
    ]
