# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-14 19:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0006_daftarmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DaftarModel',
        ),
    ]
